### PR TITLE
Websockets demo

### PR DESCRIPTION
**Pull request by pchico83**

### CODE REVIEW

**Comment by micaelgallego** [comment]
Hi Pablo, 

I see that your SUT has metricbeats installed to send metrics to EMS. ElasTest already provides a dockbeat container to monitor all Test and SUT containers when a TJob is executed. If EMS is activated in the TJob, then all logs and metrics are sent automatically to EMS instance. 

Can you please test if this behaviour is working as expected in ElasTest?

On the other hand, as we try to use ElasTest as a CI system, we don't usually create docker images for TJobs. Instead, we use a "environment image" with tools we need (Java, git, etc...) and put commands in the ElasTest GUI for cloning the git repository and execute the tests. In that way, the user can change commands interactively without rebuilding the docker image. For example, to test if EUS is working as expected, we create a TJob using ElasTest GUI and in this test we select the environment docker image 'elastest/ci-docker-e2e' and in commands with put the following: 

<pre>
git clone https://github.com/elastest/elastest-user-emulator-service; 
cd elastest-user-emulator-service/tjob-test; 
mvn test;
</pre>

In that way, we are emulating the steps a user will perform in ElasTest to use some Test Support Service.

Please can you adapt your websocket-demo to follow the same approach please? Thanks

**Comment by pchico83** [comment]
> I see that your SUT has metricbeats installed to send metrics to EMS. ElasTest already provides a dockbeat container to monitor all Test and SUT containers when a TJob is executed. If EMS is activated in the TJob, then all logs and metrics are sent automatically to EMS instance.
> 
> Can you please test if this behaviour is working as expected in ElasTest?
> 
   Nice, I will check it out!
> On the other hand, as we try to use ElasTest as a CI system, we don't usually create docker images for TJobs. Instead, we use a "environment image" with tools we need (Java, git, etc...) and put commands in the ElasTest GUI for cloning the git repository and execute the tests. In that way, the user can change commands interactively without rebuilding the docker image. For example, to test if EUS is working as expected, we create a TJob using ElasTest GUI and in this test we select the environment docker image 'elastest/ci-docker-e2e' and in commands with put the following:
> 
> git clone https://github.com/elastest/elastest-user-emulator-service; 
> cd elastest-user-emulator-service/tjob-test; 
> mvn test;
> In that way, we are emulating the steps a user will perform in ElasTest to use some Test Support Service.
> 
> Please can you adapt your websocket-demo to follow the same approach please? Thanks
> 
> 
   Do we have a GO environment image?
   I think it is a good practice to give the developer the ability to pick the image she prefers, but if we provide a GO environment image I can adapt my TJob to compile and run the test on-the-fly.

   Thanks!

**Comment by micaelgallego** [comment]
As environment image you can select the image you want. In fact, you can out the image you have used in the Dockerfile of your Test container 'golang:1.9.0-alpine3.6', but remember to install git before cloning the github repo. For that reason, we have created new images with git plus our development tools.

**Comment by pchico83** [comment]
@micaelgallego I receive the SUT logs via EMS, but I am not getting any metrics.

**Comment by micaelgallego** [comment]
Maybe there are some missconfiguration on ElasTest side. 

How can test it? Can you implement a sample test that, executed inside a TJob, logs in the console all events (logs and metrics) it is receiving? Also, is EMS documentation updated with current ports opened in EMS in which ElasTest can send metrics from SUT?

**Comment by vangarman** [comment]
@micaelgallego https://github.com/elastest/elastest-monitoring-service/blob/master/demo/ems-tests/test5/tjob.sh is an example of a tjob that connects to EMS via websockets and can print every received message.
Problems so far:
- When deploying the EMS, elastest UI doesn't show TJob/Sut logs. Debugging is very difficult.
- EMS is getting Sut logs by default, but this is not the case for Sut metrics.
@fgorostiaga can give more details on the state of the EMS docs.

**Comment by vangarman** [comment]
Closing this one, deprecated by https://github.com/elastest/elastest-monitoring-service/pull/109

**Pull request closed without merging**
